services:
  - type: web
    name: gold-signal-service
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: BOT_TOKEN
        fromDotEnv: true
      - key: CHAT_ID
        fromDotEnv: true
